#!/bin/bash -e

aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=drone > creds.json

cat creds.json

export AWS_ACCESS_KEY_ID=`cat creds.json | jq '.Credentials.AccessKeyId'`
export AWS_SECRET_ACCESS_KEY=`cat creds.json | jq '.Credentials.SecretAccessKey'`
export AWS_SESSION_TOKEN=`cat creds.json | jq '.Credentials.SessionToken'`

printenv

aws iam get-user