#!/bin/bash -e -o xtrace

aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=drone > creds.json

export AWS_ACCESS_KEY_ID=`cat creds.json | jq -r '.Credentials.AccessKeyId'`
export AWS_SECRET_ACCESS_KEY=`cat creds.json | jq -r '.Credentials.SecretAccessKey'`
export AWS_SESSION_TOKEN=`cat creds.json | jq -r '.Credentials.SessionToken'`

aws sts get-caller-identity

npm install

if [ "$PLUGIN_ACTION" = "test" ] then
    echo "running tests"
    npm run test
fi

if [ "$PLUGIN_ACTION" = "deploy" ] then
    echo "domain go!"
    node_modules/.bin/sls create_domain -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION}
    echo "deploy go!"
    node_modules/.bin/sls deploy  -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION}
fi