#!/bin/bash

set -e

if [ -z $PLUGIN_ROLE ];
then
    echo "Error: please provide aws role to assume"
    exit 1
fi

if [ -z $PLUGIN_STAGE ];
then
    echo "Error: please provide deployment stage"
    exit 1
fi

if [ -z $PLUGIN_REGION ];
then
    echo "Error: please provide aws region "
    exit 1
fi

echo "ASSUMING ${PLUGIN_ROLE}"
CREDS=`aws sts assume-role --role-arn ${PLUGIN_ROLE} --role-session-name=${DRONE_REPO_OWNER}-${DRONE_REPO_NAME}`

export AWS_ACCESS_KEY_ID=`echo $CREDS | jq -r '.Credentials.AccessKeyId'`
export AWS_SECRET_ACCESS_KEY=`echo $CREDS | jq -r '.Credentials.SecretAccessKey'`
export AWS_SESSION_TOKEN=`echo $CREDS | jq -r '.Credentials.SessionToken'`

USER=`aws sts get-caller-identity |  jq -r '.Arn'`
echo "ASSUMED $USER"


if [ "$PLUGIN_CREATE_DOMAIN" = "true" ] 
then
    echo "RUNNING CREATE DOMAIN"

    set -x
    node_modules/.bin/sls create_domain -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION} -x
    set +x
fi

if [ "$PLUGIN_ACTION" = "deploy" ] 
then
    ARGS=""
    if [ "$PLUGIN_CONCEAL" = "true" ] 
    then
        ARGS="$ARGS --conceal"
    fi

    if [ "$PLUGIN_ACCELERATE" = "true" ] 
    then
        ARGS="$ARGS --aws-s3-accelerate"
    fi
    echo "DEPLOY"

    set -x
    node_modules/.bin/sls deploy ${ARGS} -s ${PLUGIN_STAGE} -r ${PLUGIN_REGION} -v
    set +x
    
fi

